### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by 474246820** [Beseting/PhotoBrowse#2]
hello，we find a bug on the Bugly

Version ： com.github.Beseting:PhotoBrowse:v2.0.2

java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getX(MotionEvent.java:2367)
        at androidx.viewpager.widget.ViewPager.onInterceptTouchEvent(ViewPager.java:2072)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2635)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:498)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1853)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4059)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:456)
        at android.view.View.dispatchPointerEvent(View.java:13738)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5633)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5433)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4934)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4987)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4953)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5093)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4961)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5150)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4934)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4987)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4953)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4961)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4934)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7686)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7655)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7616)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7814)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:251)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:182)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Evatruy** [comment]
have same issue
